### ISSUE TITLE
无法创建c#脚本

### ISSUE THREAD

**Issue by Nebulafalls** [Daylily-Zeleen/HFSM2#1]
创建c#脚本没反应，报错
Cannot find instance binding callbacks for class 'CSharpScript'.
  Resource file not found: res://.

**Comment by Nebulafalls** [comment]
无法连接是我自己的问题，鼠标点在节点边上连不了，要点在中间点
但是c#脚本好像还是有问题

**Comment by Daylily-Zeleen** [comment]
> Cannot find instance binding callbacks for class 'CSharpScript'.
> Resource file not found: res://.

麻烦提供一下完整的错误信息，应该是有报在哪个文件哪一行的，我这边搜不到类似的错误信息

**Comment by Nebulafalls** [comment]
ERROR: Cannot find instance binding callbacks for class 'CSharpScript'.
   at: (H:\godot-cpp\src\core\class_db.cpp:321)
ERROR: Resource file not found: res://.
   at: (core/io/resource_loader.cpp:278)

**Comment by Nebulafalls** [comment]
> > Cannot find instance binding callbacks for class 'CSharpScript'.
> > Resource file not found: res://.
> 
> 麻烦提供一下完整的错误信息，应该是有报在哪个文件哪一行的，我这边搜不到类似的错误信息
ERROR: Cannot find instance binding callbacks for class 'CSharpScript'.
at: (H:\godot-cpp\src\core\class_db.cpp:321)
ERROR: Resource file not found: res://.
at: (core/io/resource_loader.cpp:278)

**Comment by Nebulafalls** [comment]
> > Cannot find instance binding callbacks for class 'CSharpScript'.
> > Resource file not found: res://.
> 
> 麻烦提供一下完整的错误信息，应该是有报在哪个文件哪一行的，我这边搜不到类似的错误信息

ERROR: Cannot find instance binding callbacks for class 'CSharpScript'.
at: (H:\godot-cpp\src\core\class_db.cpp:321)
ERROR: Resource file not found: res://.
at: (core/io/resource_loader.cpp:278)

**Comment by Daylily-Zeleen** [comment]
应该是我编译用的extension_api.json是不带c#。我以为CSharpScript至少会被当成Script。

正在修复中。

**Comment by Daylily-Zeleen** [comment]
已修复，请使用最新版本。
