### ISSUE TITLE
无法使用变量

### ISSUE THREAD

**Issue by erdongmuxin** [Daylily-Zeleen/HFSM2#2]
当我配置一个变量后,运行场景时直接退出
![image](https://github.com/Daylily-Zeleen/HFSM2/assets/50857733/24007d3a-7a60-47c4-96aa-387474a70bac)
![image](https://github.com/Daylily-Zeleen/HFSM2/assets/50857733/838db0d1-d1c7-4a4f-a60d-4508967b99f8)

**Comment by erdongmuxin** [comment]
这是我的版本
![image](https://github.com/Daylily-Zeleen/HFSM2/assets/50857733/a3fa8ebd-8780-4519-ba39-15556622e7e4)

**Comment by Daylily-Zeleen** [comment]
已于[v2.0.3](https://github.com/Daylily-Zeleen/HFSM2/releases/tag/v2.0.3)修复，请下载最新版本。

感谢你的反馈，欢迎继续反馈。
